name: Generate Static Blog

on:
  push:
    branches: [ main ]
    paths:
      - 'blog-posts.yaml'
      - 'template-blog.html'
      - 'assets/images/**'
  workflow_dispatch:  # Allows manual triggering from GitHub UI

# Add permissions to allow GitHub Actions to push to the repository
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install markdown pyyaml
    
    - name: Generate static blog posts
      run: python generate_blog.py --config_file blog-posts.yaml --template_file template-blog.html --output_dir blog
    
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add blog/
        git commit -m "Generated static blog files" || echo "No changes to commit"
        git push